version: "v1.0"
name: tt-auth

services:
  server:
    build: .
    env_file:
      - .env
    ports: 
      - "8080:8080"
    command: go run ./cmd/main.go
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"